#Site configuration
title:  Yunsoo:D
name:  Yunsoo Seo 
author: Yunsoo Seo üìÑ
# work:  Robotics engineer
work: (click my name for my CV)
year: 2001

# Navigation
nav1: "About me üòÑ"
nav2: "Education üè´"
nav3: "Projects ü§ñ"
nav4: "Publications üìú"
nav5: "Interesting paper review ‚úèÔ∏è"

# Section1
sec1: "About me üòÑ"
sec2: "Current interests ü§î"
sec3-1: >
  I am a master's student at Korea University, Department of Electrical and Electronic Engineering,<a href="http://cml.korea.ac.kr/" style="font-weight:bold ">Control and Mechatronics Lab(CML)</a>, 
  pursuing my degree under the guidance of Professor
  <a href="https://scholar.google.com/citations?user=scecuqcAAAAJ&hl=ko&oi=sra" style="color:indigo; font-weight:bold"> Myotaeg Lim</a>. 
  Concurrently, I am working as a research assistant at 
  Korea Institute of Science and Technology (KIST), <a href="https://sites.google.com/view/kist-arc/home/" style="font-weight:bold ">Advanced Robot Control Lab(ARC)</a>
  under the supervision of 
  <a href="https://scholar.google.com/citations?user=g3tJiEoAAAAJ&hl=ko&oi=sra" style="color:indigo; font-weight:bold ">Dr. Yisoo Lee </a>.
  

sec3-2:
  My research interests lie in <span style="font-weight:bold;">humanoid locomotion, sampling-based Model Predictive Control (MPC), and multi-contact dynamics</span>. 
  These are some of the topics I am currently exploring.<br>
  1Ô∏è‚É£ How can sampling-based MPC methods be scaled to handle high-dimensional humanoid systems in real-time?  <br>
  2Ô∏è‚É£ How can we incorporate uncertainty (e.g., modeling errors, sensor noise) into MPC to improve robustness in complex, dynamic environments? <br>
  3Ô∏è‚É£ How can we model and predict the interactions between a humanoid robot and its environment during multi-contact scenarios? (and how are the robot going to react? ex. GRF) <br><br>
  I believe that for robots to closely interact with humans and provide convenience, their workspace needs to expand. In this regard, I think locomotion and balance control will remain crucial research areas. Ultimately, I aim to develop household robots or disaster-response robots that can assist humans effectively.

# Section 2
sec4: "Education üè´"
sec5: >
  üë©‚Äçüéì M.S. in Korea University, Mar. 2024 - Present<br>
sec5-1: >
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è Major: Electrical and Computer Engineering   <span style="font-size: 0.7em;">(GPA: 4.5/4.5)</span><br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è Concentration: Control, Robotics and Systems <br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è <span style="font-size: 0.9em;">Graduate researcher at <a href="https://sites.google.com/view/kist-arc/home/people#h.3k1cbav6woek" style="font-weight:bold ">Advanced Robot Control Lab (ARC)</a> in Korea Institute of Science and Technology (KIST) 2024 - present</span><br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è <span style="font-size: 0.9em;">Graduate researcher at <a href="http://cml.korea.ac.kr/bbs/board.php?tbl=m_course&no=4&mode=VIEW&num=64&category=&findType=&findWord=&sort1=&sort2=&page=1" style="font-weight:bold ">Control and Mechatronics Lab (CML)</a> in Korea University 2024 - </span><br>
sec55: >
  üßë‚Äçüéì B.S. in Dongguk University, Mar. 2020 - Feb. 2024
sec55-1: >
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è Major: Mechanical, Robotics and Energy Engineering <span style="font-size: 0.7em;">(GPA: 3.69/4.5)</span> <br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è Concentration: Robotics  <br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è <span style="font-size: 0.88em;">Undergraduate researcher at <a href="https://sites.google.com/view/kist-arc/home/people#h.3k1cbav6woek" style="font-weight:bold ">Advanced Robot Control Lab (ARC)</a> at Korea Institute of Science and Technology (KIST) 2022-2023</span><br>
icon1: "fas fa-code"
icont1: "Write all the code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Section 3
sec6: "Projects ü§ñ"
sec7-250721: >
  On going project - Whole body MPPI Controller
sec8-250721: >
  ‚úîÔ∏è Model : G1, KAPEX(Awaiting public release) <br>
  ‚úîÔ∏è Method : MJPC + MPPI <br>
  -Reference paper: <br>
  <a href="https://arxiv.org/abs/2212.00541" style="font-size: 0.7em;">"Predictive Sampling: Real-time Behaviour Synthesis with MuJoCo"</a><br>
  <a href="https://arxiv.org/abs/2409.10469" style="font-size: 0.7em;">"Real-Time Whole-Body Control of Legged Robots with Model-Predictive Path Integral Control"</a><br>
  <a href="https://arxiv.org/abs/2409.15610" style="font-size: 0.7em;">"Full-Order Sampling-Based MPC for Torque-Level Locomotion Control via Diffusion-Style Annealing"</a><br>

sec7: >
  <a href="/assets/files/icros_paper.pdf" style="text-decoration: underline;"> Published: Whole body MPPI Controller</a>
sec8: >
  ‚úîÔ∏è Model : MAHRU's new model, KAPEX!(Awaiting public release) <br>
  ‚úîÔ∏è Method : Contact constraint projection dynamics + MPPI <br>
  -Reference paper: <br>
  <a href="https://arxiv.org/abs/2312.08961" style="font-size: 0.7em;">"Contact-Implicit MPC: Controlling diverse quadruped motions without pre-planned contact modes or trajectories"</a><br>
  <a href="https://ieeexplore.ieee.org/abstract/document/8255551" style="font-size: 0.7em;">"Per-Contact Iteration Method for Solving Contact Dynamics"</a><br>
  <a href="https://ieeexplore.ieee.org/abstract/document/1641993" style="font-size: 0.7em;">"Contact Consistent Control Framework for Humanoid Robots"</a><br>
sec9: "Snapped dark matter in the wild"
sec10: "MPPI CoM generator + footstep planning"
sec11: >
  ‚úîÔ∏è Model : G1 <br>
  ‚úîÔ∏è Method : MPPI CoM generator + weighted whole-body controller + footstep planning <br>
  -Reference footstep planners:<br>
  <a href="https://ieeexplore.ieee.org/abstract/document/10375162" style="font-size: 0.7em;">"Extremely Fast Computation of CoM Trajectory Generation for Walking Leveraging MPPI Algorithm"</a><br>
  <a href="https://github.com/isri-aist/BaselineFootstepPlanner" style="font-size: 0.7em;">"BaselineFootstepPlanner"</a><br>
sec12: "Adaptive dynamic programming(ADP) - On policy learning"
sec13: "Authored Report"  
sec13-1: >
  <br>
  ‚úîÔ∏è Model : Linear Inverted Pendulum Model (LIPM) <br>
  ‚úîÔ∏è Method : Adaptive dynamic programming - on-policy learning
  -Reference code <br>
  <a href="https://github.com/yu-jiang/radpbook/tree/master" style="font-size: 0.7em;">"Textbook : robust adaptive dynamic programming"</a><br>
sec14-0: >
  <a href="https://ieeexplore.ieee.org/abstract/document/10375162" style="text-decoration: underline;"> Published: Model Predictive Path Integral (MPPI) CoM generator</a>
sec15-0: >
  ‚úîÔ∏è Model : KIST - MAHRU <br>
  ‚úîÔ∏è Method : MPPI CoM generator + Inverse Kinematics (IK) controller
sec16-0: "2-Link Manipulation - MPPI Controller"
sec17-0: >
  ‚úîÔ∏è Model : 2-Link Manipulation <br>
  ‚úîÔ∏è Method : Model Predictive Path Integral (MPPI)  <br>
  -Reference papers : <br>
  <a href="https://repository.gatech.edu/entities/publication/7ca91cea-ee94-4751-9b53-54dc7a542a38 " style="font-size: 0.7em;"">"Model predictive path integral control: Theoretical foundations and applications to autonomous driving"</a><br>
  <a href="https://arc.aiaa.org/doi/full/10.2514/1.G001921" style="font-size: 0.7em;"">"Model Predictive Path Integral Control: From Theory to Parallel Computation"</a>
  
sec18-0: "humanoid CoM generator"
sec19-0: >
  ‚úîÔ∏è Model : Linear Inverted Pendulum Model (LIPM) <br>
  ‚úîÔ∏è Method : Model Predictive Control (MPC) <br>
  - Reference paper : <br>
  <a href="https://ieeexplore.ieee.org/abstract/document/4115592" style="font-size: 0.7em;"">"Trajectory-free linear model predictive control for stable walking in the presence of strong perturbations"</a>

# Section 4
sec14: "Publications üìú"
sec15: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec16: >
  <a href="https://ieeexplore.ieee.org/abstract/document/10375162" style="text-decoration: underline;">HUMANOIDS 2023: <br> Model Predictive Path Integral (MPPI) CoM generator </a>
sec17: >
  ‚úîÔ∏è Model : KIST - MAHRU <br>
  ‚úîÔ∏è Efficient MPPI-based CoM trajectory generation enabling real-time humanoid walking: <br>
  &nbsp;&nbsp; - Average computation time: 0.09 ms (2 kHz update frequency) <br>
  &nbsp;&nbsp; - Compatibility: Low-end hardware and real-time control  <br>
sec18: >
  <a href="/assets/files/ICROS_2025_poster.pdf" style="text-decoration: underline;">ICROS 2025 : <br> Whole-body MPPI Controller </a>
sec19: >
  ‚úîÔ∏è Model : MAHRU's next version, KAPEX! (Awaiting public release) <br>
  ‚úîÔ∏è MPPI-based whole-body optimization <br>
  &nbsp;&nbsp; - Target system: Validated on a 3-DoF leg system for real-time control <br>
  &nbsp;&nbsp; - Key feature: Efficient torque optimization by explicitly eliminating contact forces  <br>
sec20: "Snapped dark matter in the wild"
sec21: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Section 5
sec22: "Interesting paper review ‚úèÔ∏è"
sec23: "To be Continued....."
sec24: > 
  <a href="https://www.notion.so/time-delay-control-1e75aa3d415080fc9494feee649be539?source=copy_link" style="text-decoration: underline;"> "Robot Manipulator Control Using Decentralized Linear Time-Invariant Time-Delayed Joint Controllers"</a>
# sec25: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec25: >
  <a href="https://www.notion.so/Diffusion-style-Full-order-MPPI-torque-1ec5aa3d4150807a9b12c18a1d4149a2?source=copy_link" style="text-decoration: underline;"> ‚ÄúFull-Order Sampling-Based MPC for Torque-Level Locomotion Control via Diffusion-Style Annealing‚Äù</a>
# sec27: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec26: >
  <a href="https://www.notion.so/Vertical-Jump-of-Humanoid-robot-1f85aa3d4150806bb100fc0585954523?source=copy_link" style="text-decoration: underline;"> ‚ÄúVertical Jump of a Humanoid Robot With CoP-Guided Angular Momentum Control and Impact Absorption‚Äù</a>
sec27: >
  <a href="https://www.notion.so/HLIP-CI-MPC-1fb5aa3d41508077b557fafa9b97faea?source=copy_link" style="text-decoration: underline;"> ‚ÄúReduced-Order Model Guided Contact-Implicit Model Predictive Control for Humanoid Locomotion‚Äù</a>
sec28: >
  <a href="https://www.notion.so/ALIP-MPC-footstep-2175aa3d415080038136c8c7f80e736b?source=copy_link" style="text-decoration: underline;"> ‚ÄúBipedal Walking on Constrained Footholds with MPC Footstep Control‚Äù</a>
sec29: >
  <a href="https://www.notion.so/MJPC-MPPI-2375aa3d41508026a163d7f6f6171355?source=copy_link" style="text-decoration: underline;"> ‚ÄúReal-Time Whole-Body Control of Legged Robots with Model-Predictive Path Integral Control‚Äù</a>
sec30: >
  <a href="https://www.notion.so/CAFE-MPC-MPC-23e5aa3d4150803790e8e6c0bbbfa31f?source=copy_link" style="text-decoration: underline;"> ‚ÄúCafe-MPC: A Cascaded-Fidelity Model Predictive Control Framework with Tuning-Free Whole-Body Control‚Äù</a>
    

# Social Links
# facebook: username
# twitter:  username
#google: username
#instagram: username
#pinterest: username
linkedin: ys-seo-214034323
youtube: HumARCnoid
#spotify: username
#lastfm: username
github: yunsooSeo
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
# keybase: username
google_scholar: citations?user=xPhWctkAAAAJ&hl=ko&oi=sra
email: 01aggiggi@gmail.com
