#Site configuration
title:  YunSoo:D
name:  YunSoo Seo 
author: Yunsoo Seo üìÑ
# work:  Robotics engineer
work: (click my name for my CV)
year: 2001

# Navigation
nav1: "About me üòÑ"
nav2: "Educations üè´"
nav3: "Projects ü§ñ"
nav4: "Publications üìú"
nav5: "Journey ‚úèÔ∏è"

# Section1
sec1: "About me üòÑ"
sec2: "Current interests ü§î"
sec3-1: >
  I am a master's student at Korea University, <a href="http://cml.korea.ac.kr/" style="font-weight:bold ">Control and Mechatronics Lab</a>, 
  pursuing my degree under the guidance of Professor
  <a href="https://scholar.google.com/citations?user=scecuqcAAAAJ&hl=ko&oi=sra" style="color:indigo; font-weight:bold"> Myotaeg Lim</a>. 
  Concurrently, I work as a research assistant at the 
  Korea Institute of Science and Technology (KIST), <a href="https://sites.google.com/view/kist-arc/home/" style="font-weight:bold ">Advanced Robot Control Lab(ARC)</a>
  under the supervision of 
  <a href="https://scholar.google.com/citations?user=g3tJiEoAAAAJ&hl=ko&oi=sra" style="color:indigo; font-weight:bold ">Dr. Yisoo Lee </a>.
  

sec3-2:
  My research interests lie in <span style="font-weight:bold;">humanoid locomotion, sampling-based Model Predictive Control (MPC), and multi-contact dynamics</span>. 
  These are some that I am diving into these days.<br>
  1Ô∏è‚É£ How can sampling-based MPC methods be scaled to handle high-dimensional humanoid systems in real-time?  <br>
  2Ô∏è‚É£ How can we incorporate uncertainty (modeling errors, sensor noise etc.) into MPC to improve robustness in complex, dynamic environments? <br>
  3Ô∏è‚É£ How can we model and predict the interactions between a humanoid robot and its environment during multi-contact scenarios?(and how are the robot gonna react? ex. GRF) <br><br>
  I believe that for robots to closely interact with humans and provide convenience, their workspace needs to expand. In this regard, I think locomotion and balancing will remain crucial research areas. Ultimately, I aim to develop household robots or disaster-response robots that can assist humans effectively.

# Section 2
sec4: "Educations üè´"
sec5: >
  üë©‚Äçüéì M.S in Electrical and Computer Engineering, Mar. 2024 - Present<br>
sec5-1: >
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è Major: Control, Robotics and Systems. Korea University <span style="font-size: 0.7em;">(GPA: 4.5/4.5)</span><br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è <span style="font-size: 0.9em;">Graduate researcher of <a href="https://sites.google.com/view/kist-arc/home/people#h.3k1cbav6woek" style="font-weight:bold ">Advanced Robot Control Lab(ARC)</a> in Korea Institute of Science and Technology (KIST) 2024 - </span><br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è <span style="font-size: 0.9em;">Graduate researcher of <a href="http://cml.korea.ac.kr/bbs/board.php?tbl=m_course&no=4&mode=VIEW&num=64&category=&findType=&findWord=&sort1=&sort2=&page=1" style="font-weight:bold ">Control and Mechatronics Lab</a> in Korea University 2024 - </span><br>
sec55: >
  üßë‚Äçüéì B.S in Mechanical, Robotics and Energy Engineering, Mar.2020 - Feb. 2024
sec55-1: >
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è Robotics. Dongguk University <span style="font-size: 0.7em;">(GPA: 3.69/4.5)</span><br>
  &nbsp;&nbsp;&nbsp;&nbsp; ‚úîÔ∏è <span style="font-size: 0.88em;">Undergraduate researcher of <a href="https://sites.google.com/view/kist-arc/home/people#h.3k1cbav6woek" style="font-weight:bold ">Advanced Robot Control Lab(ARC)</a> in Korea Institute of Science and Technology (KIST) 2022-2023</span><br>
icon1: "fas fa-code"
icont1: "Write all the code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Section 3
sec6: "Projects ü§ñ"
sec7: "On going project : Contact - implicit MPPI"
sec8: >
  ‚úîÔ∏è Model: MAHRU's new model!(Awaiting public release)
  ‚úîÔ∏è Method: Contact dynamics + Bisection method + MPPI
  -Reference paper: <br>
  <a href="https://arxiv.org/abs/2312.08961" style="font-size: 0.7em;">"Contact-Implicit MPC: Controlling diverse quadruped motions without pre-planned contact modes or trajectories"</a><br>
  <a href="https://ieeexplore.ieee.org/abstract/document/8255551" style="font-size: 0.7em;">"Per-Contact Iteration Method for Solving Contact Dynamics"</a><br>
  <a href="https://arxiv.org/abs/2103.16021" style="font-size: 0.7em;">"Fast and Feature-Complete Differentiable Physics for Articulated Rigid Bodies with Contact"</a><br>
sec9: "Snapped dark matter in the wild"
sec10: "MPPI CoM generator + footstepplanning"
sec11: >
  ‚úîÔ∏è Model : G1 <br>
  ‚úîÔ∏è Method : MPPI CoM generator + weighted whole body controller + foot step planning <br>
  -Reference foot step planner:<br>
  <a href="https://ieeexplore.ieee.org/abstract/document/10375162" style="font-size: 0.7em;">"Extremely Fast Computation of CoM Trajectory Generation for Walking Leveraging MPPI Algorithm"</a><br>
  <a href="https://github.com/isri-aist/BaselineFootstepPlanner" style="font-size: 0.7em;">"BaselineFootstepPlanner"</a><br>
sec12: "Adaptive dynamic programming(ADP) - On policy learning"
sec13: "Authored Report"  
sec13-1: >
  <br>
  ‚úîÔ∏è Model : Linear Inverted Pendulum Model (LIPM) <br>
  ‚úîÔ∏è Method: Adaptavie dynamic programming - on policy learning
  -Reference code <br>
  <a href="https://github.com/yu-jiang/radpbook/tree/master" style="font-size: 0.7em;">"Textbook : robust adaptive dynamic programming"</a><br>
sec14-0: >
  <a href="https://ieeexplore.ieee.org/abstract/document/10375162" style="text-decoration: underline;"> Published: Model Predictive Path Integral (MPPI) CoM generator</a>
sec15-0: >
  ‚úîÔ∏è Model : KIST - MAHRU <br>
  ‚úîÔ∏è Method : MPPI CoM generator + Inverse Kinematics(IK) Controller
sec16-0: "2 Link Manipulation - MPPI Controller"
sec17-0: >
  ‚úîÔ∏è Model : 2 Link Manipulation <br>
  ‚úîÔ∏è Method : Model predictive path Integral(MPPI)  <br>
  -Reference paper : <br>
  <a href="https://repository.gatech.edu/entities/publication/7ca91cea-ee94-4751-9b53-54dc7a542a38 " style="font-size: 0.7em;"">"Model predictive path integral control: Theoretical foundations and applications to autonomous driving"</a>
  <a href="https://arc.aiaa.org/doi/full/10.2514/1.G001921" style="font-size: 0.7em;"">"Model Predictive Path Integral Control: From Theory to Parallel Computation"</a>
  
sec18-0: "humanoid CoM generator"
sec19-0: >
  ‚úîÔ∏è Model : Linear Inverted Pendulum Model(LIPM) <br>
  ‚úîÔ∏è Method : Model predictive control(MPC) <br>
  - Reference paper : <br>
  <a href="https://ieeexplore.ieee.org/abstract/document/4115592" style="font-size: 0.7em;"">"Trajectory free linear model predictive control for stable walking in the presence of strong perturbations"</a>

# Section 4
sec14: "Publications üìú"
sec15: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec16: >
  <a href="https://ieeexplore.ieee.org/abstract/document/10375162" style="text-decoration: underline;">HUMANOIDS 2023: <br> Model Predictive Path Integral (MPPI) CoM generator </a>
sec17: >
  ‚úîÔ∏è Model : KIST - MAHRU <br>
  ‚úîÔ∏è Efficient MPPI-based CoM trajectory generation enabling real-time humanoid walking: <br>
  &nbsp;&nbsp; - Average computation time: 0.09 ms (2 kHz update frequency) <br>
  &nbsp;&nbsp; - Compatibility: Low-end hardware and real-time control  <br>
sec18: "Terraformed a small moon"
sec19: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec20: "Snapped dark matter in the wild"
sec21: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Section 5
sec22: "Journey ‚úèÔ∏è"
sec23: "To be Continued....."
sec24: "Possibly broke spacetime"
sec25: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec26: "Terraformed a small moon"
sec27: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec28: "Snapped dark matter in the wild"
sec29: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Social Links
# facebook: username
# twitter:  username
#google: username
#instagram: username
#pinterest: username
linkedin: ys-seo-214034323
youtube: ysseo753
#spotify: username
#lastfm: username
github: yunsooSeo
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
# keybase: username
google_scholar: citations?user=xPhWctkAAAAJ&hl=ko&oi=sra
email: 01aggiggi@gmail.com

